// Code generated by bomlok. DO NOT EDIT.

package example


// Bomlok_GetValue returns the value of the field with the given name for Person
func (s *Person) Bomlok_GetValue(field string) any {
	switch field {
	case "FirstName":
		return s.FirstName
	case "LastName":
		return s.LastName
	case "Age":
		return s.Age
	case "Email":
		return s.Email
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for Person
func (s *Person) Bomlok_Fields() []string {
	return []string{
		"FirstName",
		"LastName",
		"Age",
		"Email",
		
	}
}

// Bomlok_GetValue returns the value of the field with the given name for Address
func (s *Address) Bomlok_GetValue(field string) any {
	switch field {
	case "Street":
		return s.Street
	case "City":
		return s.City
	case "State":
		return s.State
	case "ZipCode":
		return s.ZipCode
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for Address
func (s *Address) Bomlok_Fields() []string {
	return []string{
		"Street",
		"City",
		"State",
		"ZipCode",
		
	}
}

// Bomlok_GetValue returns the value of the field with the given name for Company
func (s *Company) Bomlok_GetValue(field string) any {
	switch field {
	case "Name":
		return s.Name
	case "Employees":
		return s.Employees
	case "Revenue":
		return s.Revenue
	case "Public":
		return s.Public
	default:
		return nil
	}
}

// Bomlok_Fields returns all field names for Company
func (s *Company) Bomlok_Fields() []string {
	return []string{
		"Name",
		"Employees",
		"Revenue",
		"Public",
		
	}
}

